[package]
name = "c_compiler"
version = "0.1.0"
edition = "2021"
resolver = "2"

[features]
default = ["run_in_axle"]
run_in_axle = []

[dependencies]
axle_rt = {path = "../axle_rt" }
axle_rt_derive = {path = "../axle_rt_derive" }
cstr_core = "0.2.4"
