#ifndef PS2_CONTROLLER_H
#define PS2_CONTROLLER_H

#define PS2_RECV_PORT 0x60
#define PS2_SEND_PORT 0x64
#define PS2_CMD_PORT 0x64
#define PS2_DATA 0x60

#define PS2_CMD_ENABLE_DEVICE_1 0xAE
#define PS2_CMD_DISABLE_DEVICE_1 0xAD
#define PS2_CMD_ENABLE_DEVICE_2 0xA8
#define PS2_CMD_DISABLE_DEVICE_2 0xA7
#define PS2_CMD_TEST_CONTROLLER 0xAA
#define PS2_CMD_RESP_TEST_CONTROLLER_SUCCESS 0x55
#define PS2_CMD_RESP_TEST_CONTROLLER_FAILURE 0xFC
#define PS2_CMD_TEST_DEVICE_1 0xAB
#define PS2_CMD_TEST_DEVICE_2 0xA9
#define PS2_CMD_RESP_TEST_DEVICE_SUCCESS 0x00
#define PS2_CMD_RESET_DEVICE 0xFF
#define PS2_CMD_WRITE_NEXT_BYTE_TO_SECOND_INPUT_PORT 0xD4

#define PS2_CMD_READ_CONTROLLER_CONFIGURATION_BYTE 0x20
#define PS2_CMD_SET_CONTROLLER_CONFIGURATION_BYTE 0x60

// Device responses
#define PS2_DEV_ACK 0xFA
#define PS2_DEV_RESET_ACK 0xAA

void ps2_init(void);
void ps2_enable_keyboard(void);
void ps2_enable_mouse(void);

#endif