[package]
name = "libgui_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "libgui_derive"
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
agx_definitions = {path = "../agx_definitions" }
# libgui = {path = "../libgui" }
