[workspace]
members = [
    "agx_definitions",
    "awm_messages",
    "axle_rt",
    "axle_rt_derive",
    "file_browser",
    "file_manager_messages",
    "gb_emu",
    "initrd_fs",
    "libfs",
    "libgui",
]
