[workspace]
resolver = "2"
members = [
    "agx_definitions",
    "awm_messages",
    "axle_rt",
    "axle_rt_derive",
    "file_browser",
    "file_manager_messages",
    "initrd_fs",
    "libfs",
    "libgui",
]

exclude = [
    # PT: Disabled in axle target until stable with a PAL
    # Currently only runs on std host
    "gb_emu",
]