[package]
name = "ttf_renderer"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
axle_rt = {path = "../axle_rt" }
axle_rt_derive = {path = "../axle_rt_derive" }
agx_definitions = {path = "../agx_definitions"}
num-traits = { version = "0.2", default-features = false, features = ["libm"]}
itertools = { version = "0.10.5", default-features = false }
