[package]
name = "mkinitrd"
version = "0.1.0"
edition = "2021"

[dependencies]
axle_rt = {path = "../../rust_programs/axle_rt", features = ["testing"] }
libfs = { path = "../../rust_programs/libfs" }
cstr_core = "*"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_bytes = { version = "0.11", default-features = false }
postcard = { version = "0.7.2", features = ["alloc"] }
pathdiff = "0.2.1"
