[package]
name = "sata_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
axle_rt = { path = "../axle_rt" }
axle_rt_derive = {path = "../axle_rt_derive" }

[dependencies.bitvec]
version = "1"
default-features = false
features = ["alloc"]
