[package]
name = "libgui"
version = "0.1.0"
edition = "2021"

[features]
run_with_std = ["pixels", "winit"]

[dependencies]
cstr_core = "0.2.4"
rand_core = { version = "0.5.1", default-features = false }
rand = { version = "0.5.1", default-features = false }

axle_rt = {path = "../axle_rt" }
axle_rt_derive = {path = "../axle_rt_derive" }
awm_messages = {path = "../awm_messages" }
agx_definitions = {path = "../agx_definitions" }
libgui_derive = {path = "../libgui_derive"}

# These dependencies are only enabled in use_std mode
pixels = { version = "0.9.0", optional = true }
winit = { version = "*", optional = true }

# PT: For f64.abs() in no_std contexts
[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]
