name: axle CI

# Configure when the workflow runs
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, uefi-bootloader, build-in-ci ]
  pull_request:
    branches: [ master, uefi-bootloader, build-in-ci ]

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-sysroot-and-toolchain:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # Requires Python >= 3.9 for str.removesuffix()
          python-version: '3.9'

      # Runs a set of commands using the runners shell
      - name: Build axle toolchain
        shell: bash
        run: |
          set -x
          python3 scripts/build_os_toolchain.py --install_dependencies
          echo "Toolchain built successfully"
        
      - uses: actions/upload-artifact@v2
        with:
          name: sysroot-and-toolchain
          path: |
            x86_64-toolchain
            axle-sysroot

  build-kernel:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # Requires Python >= 3.9 for str.removesuffix()
          python-version: '3.9'

      - name: Install dependencies
        shell: bash
        run: |
          set -x
          # Install dependencies
          python3 scripts/build_os_toolchain.py --install_dependencies_only
        
      - uses: actions/download-artifact@v2
        with:
          name: sysroot-and-toolchain

      - name: Build kernel
        shell: bash
        run: |
          python3 scripts/build_kernel_headers.py
          python3 scripts/build_kernel.py
      
      # TODO(PT): Upload an iso image as an artifact?
