name: axle CI

# Configure when the workflow runs
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, uefi-bootloader, build-in-ci ]
  pull_request:
    branches: [ master, uefi-bootloader, build-in-ci ]

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-sysroot-and-toolchain:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # Requires Python >= 3.9 for str.removesuffix()
          python-version: '3.9'
          # https://github.com/actions/setup-python#caching-packages-dependencies
          # cache: 'pip'
          # cache-dependency-path: 'python-dependencies.txt'
      - run: pip install -r python-dependencies.txt

      - name: Build axle toolchain
        shell: bash
        run: |
          python3 scripts/install_dependencies.py
          python3 scripts/build_os_toolchain.py
          echo "Toolchain built successfully"
        
      - uses: actions/upload-artifact@v2
        with:
          name: sysroot-and-toolchain
          path: |
            x86_64-toolchain
            axle-sysroot

  build-kernel:
    runs-on: ubuntu-latest
    needs: build-sysroot-and-toolchain

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # Requires Python >= 3.9 for str.removesuffix()
          python-version: '3.9'
          # https://github.com/actions/setup-python#caching-packages-dependencies
          # cache: 'pip'
          # cache-dependency-path: 'python-dependencies.txt'
      - run: pip install -r python-dependencies.txt
        
      - uses: actions/download-artifact@v2
        with:
          name: sysroot-and-toolchain

      - name: Build kernel
        shell: bash
        run: |
          git submodule update --init --recursive
          python3 scripts/build_kernel_headers.py
          python3 scripts/build_kernel.py
      
      # TODO(PT): Upload an iso image as an artifact?
